# Numpy

Numpy is the library used in Python for high performance multidimensional array objects, and it provides a lot of tools and functions for manipulating these objects. 

For using numpy we must first import this package like so

In [2]:
import numpy as np

Here we use `as np` so that we don't have to write `numpy` everytime we use any function of numpy and we can just use `np` in it's place. For example we can use the following code to initialize a numpy array

In [3]:
a = np.array([2,3,4])
print(type(a))
print(a.shape)
print(a[2])
a[2] = 5;
print(a)

<class 'numpy.ndarray'>
(3,)
4
[2 3 5]


As we can see the datatype of a numpy array is `np.ndarray`. We can directly print the array in numpy without having to iterate over its elements. Also to access any single element of the array we use `[]`.

We can also initialize multi-dimensional arrays like so

In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(type(b))
print(b)

(2, 3)
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


`Shape` is the attribute of a numpy array which tells us the dimensions of the array. Here `b` is a 2x3 array .Note that type of B is still `np.ndarray`.

We can also create a numpy array of given dimensions filled with ones like so

In [5]:
c = np.ones((2,3))
c

array([[1., 1., 1.],
       [1., 1., 1.]])

To fill it with some other constant value we do this

In [6]:
c = np.full((3,4),10)
c

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

We can also fill the array with random elements between 0 and 1 like so


In [7]:
c = np.random.random((2,3))
c

array([[0.00357354, 0.15675229, 0.46593929],
       [0.55219491, 0.41845687, 0.25433196]])

Another way we can make a np array is using `arange` which fills the array with numbers withing a certain range. For example

In [8]:
a = np.arange(5)
print(a)
a = np.arange(3,7)
print(a)
a = np.arange(3,10,2)
print(a)

[0 1 2 3 4]
[3 4 5 6]
[3 5 7 9]


Like lists, numpy arrays can also be sliced like so

In [9]:
d = c[:1, 1:3]
d

array([[0.15675229, 0.46593929]])

However if we chage the elements of the sliced array, the original array is also affected

In [10]:
d[0][0] = 5
c

array([[3.57353614e-03, 5.00000000e+00, 4.65939291e-01],
       [5.52194912e-01, 4.18456874e-01, 2.54331955e-01]])

We can use array slicing to view only certain rows or only certain columns like so

In [11]:
print(c[1,:]) #Print only second row
print(c[:,1]) #Print only second column

[0.55219491 0.41845687 0.25433196]
[5.         0.41845687]


We can also index into 2d arrays using `,` rather than using `[]` like so

In [24]:
a = np.array([[1,2],[2,3]])
print(a[0,0])

1


Numpy arrays have a special property that the index of numpy arrays may be numpy arrays themselves. For example in the following code

In [23]:
a = np.array([[3,4,5],[5,6,7],[7,8,9],[8,9,10]])
print(a)
print("- - - - - -")
b = [0,1,2,1]
c = [1,2,0,2]
print(a[b,c])

[[ 3  4  5]
 [ 5  6  7]
 [ 7  8  9]
 [ 8  9 10]]
- - - - - -
[4 7 7 7]


How this works is that it takes each element of those arrays as a single index, and returns those elements in a numpy array of its own. This is very useful in a lot of areas where we may want to use a number of elements of the array without using loops. The thing to remember here is that the array we obtain is of the shape of the index arrays, not the array being indexed. This is fancy indexing

We can also use logical statements as indexes. This is called masked indexing

In [26]:
d = np.array([1,2,3,4,5,6,7,8,9,10])
d[d>5]

array([ 6,  7,  8,  9, 10])

Using `type` on np arrays returns us `np.ndarray`. To find the datatype of the elements of the array we use `dtype` as follows

In [28]:
d.dtype

dtype('int32')

For basic mathematical operations on arrays, both operators as well as fucntions may be used

In [30]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

print("Addition")
print(x+y)
print("--------")
print(np.add(x,y))

print("Multiplication")
print(x*y)
print("--------")
print(np.multiply(x,y))

print("Element wise Division")
print(x/y)
print("--------")
print(np.divide(x,y))

print("Subtraction")
print(x - y)
print("--------")
print(np.subtract(x,y))





Addition
[ 6  8 10 12]
--------
[ 6  8 10 12]
Multiplication
[ 5 12 21 32]
--------
[ 5 12 21 32]
Element wise Division
[0.2        0.33333333 0.42857143 0.5       ]
--------
[0.2        0.33333333 0.42857143 0.5       ]
Subtraction
[-4 -4 -4 -4]
--------
[-4 -4 -4 -4]


The thing to remember here is that all these are element wise operations, especially in the case for multiplication and division. The other element wise operation availabe is square root

In [31]:
print(np.sqrt(x))

[1.         1.41421356 1.73205081 2.        ]


Like mentioned above, `*` is the operator for element wise multiplication of matrices. For dot product we do it in the following two ways

In [32]:
print(x.dot(y))

print(np.dot(x,y))

70
70


Numpy also has built in functions for summing over the elemnt of the array, like so

In [35]:
a = np.array([[3,4,5],[5,6,7],[7,8,9],[8,9,10]])
print(np.sum(a)) #Prints sum of all elements of a
print(" - - - - -")
print(np.sum(a, axis = 0)) #Prints sum of each column of a
print("- - - - - -")
print(np.sum(a, axis = 1)) #Prints sum of each row of a

81
 - - - - -
[23 27 31]
- - - - - -
[12 18 24 27]


We can also easily transpose an array in numpy like so

In [37]:
print(a)
print("- - - - -")
print(a.T)

[[ 3  4  5]
 [ 5  6  7]
 [ 7  8  9]
 [ 8  9 10]]
- - - - -
[[ 3  5  7  8]
 [ 4  6  8  9]
 [ 5  7  9 10]]


This is a very helpful operation in a number of operations in matrices, and particularly useful in calculating the losses and weights in machine learning

Broadcasting is a very useful operation in numpy which allows us to use a smaller array to manipulate a bigger one. It is used in the following way

In [38]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([1,2,3])
print(x+y)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


Because of numpy broadcasting, even though the shapes of x and y are different, numpy allows the second matrix to be added to all rows of the first one. This allows us to easily use any smaller matrix to manipulate bigger ones without stacking copies or making new matrices.

We can also use broadcasting to compute the cross product of matrices in the following way

In [39]:
a = np.array([1,3,5])
b = np.array([2,4])
print(np.reshape(a,(3,1)) * b)

[[ 2  4]
 [ 6 12]
 [10 20]]


Broadcasting is one of the most useful and versatile tools of numpy, and helps make the code much less bulky when we want to do operations on arrays. 